src/presenter/models/movie.py
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Index
from sqlalchemy.orm import relationship
from presenter.app import db
import datetime
from sqlalchemy.orm import validates
import ipdb


class Movie(db.Model):
    __tablename__ = "movies"
    id = Column(Integer, nullable=False, primary_key=True, unique=True)
    genre = Column(String(255))
    date_of_scraping = Column(String(12))
    directors = Column(String(255))
    title = Column(String(255), nullable=False)
    rating = Column(Integer)
    release_year = Column(Integer, nullable=True)
    top_cast = Column(String(300))
    url = Column(String(255), nullable=False)
    uid = Column(String(9), nullable=False)
    image_url = Column(String(250))
    image_path = Column(String(250))

    def __repr__(self):
        return "<Movie id=%s %r>" % (self.uid, self.title)

    @validates("uid", "title", "url")
    def validate_uid(self, key, values):
        if key == "uid":
            assert values != "", "uid not valid"
        if key == "title":
            assert values != "", "title can not be blank"
        if key == "url":
            assert values != "", "url can nor be blank"

        return values

src/presenter/controllers/movies.py
from flask import Flask, Blueprint, jsonify, render_template, url_for, request, redirect, flash
from werkzeug.utils import secure_filename
import os

movies_blueprint = Blueprint("movies", __name__)

from presenter.app import app, db
from presenter.models.movie import Movie
import ipdb
import json
from presenter.app import app, db, ALLOWED_EXTENSIONS, UPLOAD_FOLDER


def allowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


@movies_blueprint.route("/movies/")
def index():
    all_movies = Movie.query.order_by(Movie.id).all()
    per_page = request.args.get("items", 5, type=int)
    current_page = request.args.get("page", 1, type=int)

    movie_count = len(all_movies)

    start = per_page * (current_page - 1)
    end = min(start + per_page, movie_count)
    movies = all_movies[start:end]
    mess = ""
    if len(movies) == 0:
        mess = "Error message, no more items"

    return render_template(
        "movies/index.html", movies=movies, current_page=current_page, items_per_page=per_page, mess=mess
    )


def to_list(dbstring):
    dbstring = dbstring.strip("][")
    li = dbstring.split(", ")
    result = []
    for item in li:
        result.append((item[1:-1]))
    return result


@movies_blueprint.route("/movies/<id>")
def show(id):
    query = Movie.query.filter_by(id=id).all()
    if query:
        movie = query[0]
        actors = to_list(movie.top_cast)
        print(movie.top_cast)
        return render_template("movies/movie.html", movie=movie, actors=actors)
    else:
        return render_template("movies/index.html")


@movies_blueprint.route("/movies/new")
def new():
    return render_template("movies/new.html")


@movies_blueprint.route("/movies/new", methods=["POST"])
def create():
    try:
        movie = Movie(
            genre=request.form.get("genre"),
            date_of_scraping=request.form.get("date_of_scraping"),
            directors=request.form.get("directors"),
            title=request.form.get("title"),
            rating=request.form.get("rating"),
            release_year=request.form.get("release_year"),
            top_cast=request.form.get("top_cast"),
            url=request.form.get("url"),
            uid=request.form.get("uid"),
            image_url=request.form.get("image_url"),
            image_path=request.form.get("image_path"),
        )

        db.session.add(movie)
        db.session.commit()
    except AssertionError as errors:
        return render_template("movies/new.html", errors=errors)

    return redirect("/movies")


@movies_blueprint.route("/movies/<id>/edit")
def edit(id):
    query = Movie.query.filter_by(id=id).all()
    if query:
        movie = query[0]
        return render_template("movies/edit.html", movie=movie)
    else:
        return render_template("movies/index.html")


@movies_blueprint.route("/movies/<id>/edit", methods=["POST"])
def update(id):
    movie = Movie.query.get(id)
    try:
        # ipdb.set_trace()
        genre = (request.form.get("genre"),)
        date_of_scraping = (request.form.get("date_of_scraping"),)
        directors = (request.form.get("directors"),)
        title = (request.form.get("title"),)
        rating = (request.form.get("rating"),)
        release_year = (request.form.get("release_year"),)
        top_cast = (request.form.get("top_cast"),)
        url = (request.form.get("url"),)
        uid = (request.form.get("uid"),)
        image_url = (request.form.get("image_url"),)
        image_path = request.form.get("image_path")

        movie.genre = genre[0]
        movie.date_of_scraping = date_of_scraping[0]
        movie.directors = directors[0]
        movie.title = title[0]
        movie.rating = rating[0]
        movie.release_year = release_year[0]
        movie.top_cast = top_cast[0]
        movie.url = url[0]
        movie.uid = uid[0]
        movie.image_url = image_url[0]
        movie.image_path = image_path[0]

        db.session.flush()
        db.session.commit()
    except AssertionError as errors:
        return render_template("movies/edit.html", errors=errors)

    return redirect("/movies")


@movies_blueprint.route("/movies/upload", methods=["POST"])
def upload():
    if "file" not in request.files:
        flash("No file part")
        return render_template("/upload/index.html")
    file = request.files["file"]
    if file and allowed_file(file.filename):
        for row in file.readlines():
            temp = json.loads(row)
            movie = Movie()
            movie.title = temp.get("title")
            movie.uid = temp.get("uid")
            movie.url = temp.get("url")
            movie.genre = str(temp.get("genre"))
            movie.directors = str(temp.get("directors"))
            movie.date_of_scraping = str(temp.get("date_of_scraping"))
            movie.rating = temp.get("rating")
            # movie.release_year = int(temp.get("release_year"))
            movie.top_cast = str(temp.get("top_cast"))
            # movie.image_url = temp.get("image_url")
            # movie.image_path = str(temp.get("image_path"))

            db.session.add(movie)
        db.session.flush()
        db.session.commit()

        filename = secure_filename(file.filename)
        file.save(os.path.join(app.config["UPLOAD_FOLDER"], filename))
        print(file)
        # ipdb.set_trace()
        flash("Successfully uploaded file")
    else:
        flash("Unallowed file type")

    return render_template("/upload/index.html")

src/presenter/templates/movies/edit.html
{% extends 'homepage/index.html' %}
{% block content %}

<p>Update {{movie.title}}</p>

    <form method="post" url="{{ url_for('movies.update', id=movie['id']) }}">
        <label for="movie">Movie</label>
        <br>
        <input type="text" name="genre" placeholder="genre" value ="{{ movie.genre }}"></input>
        <input type="text" name="directors" placeholder="directors" value ="{{ movie.directors }}"></input>
        <input type="text" name="title" placeholder="Movie title" value ="{{ movie.title }}"></input>
        <input type="text" name="rating" placeholder="Movie rating" value ="{{ movie.rating }}"></input>
        <input type="text" name="release_year" placeholder="Movie release_year" value ="{{ movie.release_year }}"></input>
        <input type="text" name="top_cast" placeholder="Movie top_cast" value ="{{ movie.top_cast }}"></input>
        <input type="text" name="url" placeholder="Movie url" value ="{{ movie.url }}"></input>
        <input type="text" name="uid" placeholder="Movie uid" value ="{{ movie.uid }}"></input>
        <input type="text" name="image_url" placeholder="Movie image_url" value ="{{ movie.image_url }}"></input>
        <input type="text" name="image_path" placeholder="Movie image_path" value ="{{ movie.image_path }}"></input>

        <button type="submit">Submit</button>
    </form>

    {% if errors %}
        {{ errors }}
    {%endif%}
{% endblock %}

src/presenter/templates/movies/index.html
{% extends 'homepage/index.html' %}
{% block content %}
<p>Movie list</p>
<ul>
        {% if current_page == 1 %}
            <li>
                <a  href="#">Previous</a></li>
        {% else %}
            <li>
                <a href="{{ url_for('movies.index', page=current_page - 1, items=items_per_page) }}">Previous</a></li>
        {% endif %}
        <li>
                <a class="button-next" href="{{ url_for('movies.index', page=current_page + 1, items=items_per_page) }}">Next</a></li>
</ul>
 {% for movie in movies %}
    <p><a href="{{ movie.id }}">{{ movie.title }}</a></p>
{% endfor %}
<br>
<a href="/movies/new">Add new movie</a>

{% endblock %}

src/presenter/templates/movies/movie.html
{% extends 'homepage/index.html' %}
{% block content %}
<p>Movie</p>
<p>{{movie["title"]}}</p>

<ul>
	{% for actor in actors %}
        <li>
            <p>{{actor}}</p>

            
        </li>
        <hr>
    {% endfor %}
</ul>

<a href="{{ url_for('movies.update', id=movie.id) }}">Edit Movie</a>
{% endblock %}

src/presenter/templates/movies/new.html
{% extends 'homepage/index.html' %}
{% block content %}
<p>Create a new movie</p>
    <form method="post" url='/movies/new'>
        <label for="movie">Movie</label>
        <br>
        <input type="text" name="genre" placeholder="genre"></input>
        <input type="text" name="date_of_scraping" placeholder="date_added"></input>
        <input type="text" name="directors" placeholder="directors"></input>
        <input type="text" name="title" placeholder="Movie title"></input>
        <input type="text" name="rating" placeholder="Movie rating"></input>
        <input type="text" name="release_year" placeholder="Movie release_year"></input>
        <input type="text" name="top_cast" placeholder="Movie top_cast"></input>
        <input type="text" name="url" placeholder="Movie url"></input>
        <input type="text" name="uid" placeholder="Movie uid"></input>
        <input type="text" name="image_url" placeholder="Movie image_url"></input>
        <input type="text" name="image_path" placeholder="Movie image_path"></input>

        <button type="submit">Submit</button>
    </form>

    {% if errors %}
        {{ errors }}
    {%endif%}
{% endblock %}