src/presenter/models/actor.py
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Index
from sqlalchemy.orm import relationship
from presenter.app import db
from sqlalchemy.orm import validates
import ipdb


class Actor(db.Model):
    __tablename__ = "actors"
    id = Column(Integer, nullable=False, primary_key=True, unique=True)
    name = Column(String(255), nullable=False)
    uid = Column(String(10), nullable=False)
    filmography_movie_url = Column(String(500))
    filmography_movie_title = Column(String(500))

    def __repr__(self):
        return "<Actor id=%s %r>" % (self.id, self.name)

    @validates("uid", "name")
    def validate_fields(self, keys, values):
        if keys == "uid":
            assert values != "", "uid is not valid"
        if keys == "name":
            assert values != "", "name is not valid"
        return values

src/presenter/controllers/actors.py
from flask import Flask, Blueprint, jsonify, render_template, url_for, request, redirect, flash
from werkzeug.utils import secure_filename
import os

actors_blueprint = Blueprint("actors", __name__)

from presenter.app import app, db
from presenter.models.actor import Actor
import ipdb
import json
from presenter.app import app, db, ALLOWED_EXTENSIONS, UPLOAD_FOLDER


def allowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


@actors_blueprint.route("/actors/")
def index():
    all_actors = Actor.query.order_by(Actor.id).all()
    per_page = request.args.get("items", 5, type=int)
    current_page = request.args.get("page", 1, type=int)

    actors_count = len(all_actors)

    start = per_page * (current_page - 1)
    end = min(start + per_page, actors_count)
    actors = all_actors[start:end]
    error = ""
    if len(actors) == 0:
        error = "Error message, no more items"

    return render_template(
        "actors/index.html", actors=actors, current_page=current_page, items_per_page=per_page, error=error
    )


def to_list(dbstring):
    dbstring = dbstring.strip("][")
    li = dbstring.split(", ")
    result = []
    for item in li:
        result.append((item[1:-1]))
    return result


@actors_blueprint.route("/actors/<id>")
def show(id):
    item = Actor.query.get(id)
    filmography_name = item.filmography_movie_title
    filmography_url = item.filmography_movie_url
    filmography = [x for x in zip(to_list(filmography_name), to_list(filmography_url))]
    return render_template("/actors/actor.html", actor={"name": item.name, "filmography": filmography, "id": item.id})


@actors_blueprint.route("/actors/new")
def new():
    return render_template("actors/new.html")


@actors_blueprint.route("/actors/new", methods=["POST"])
def create():
    try:
        actor = Actor(
            name=request.form.get("name"),
            uid=request.form.get("uid"),
            filmography_movie_url=request.form.get("filmography_movie_url"),
            filmography_movie_title=request.form.get("filmography_movie_title"),
        )

        db.session.add(actor)
        db.session.commit()
    except AssertionError as errors:
        return render_template("/actors/new.html", errors=errors)

    return redirect("/actors")


@actors_blueprint.route("/actors/<id>/edit")
def edit(id):
    query = Actor.query.filter_by(id=id).all()
    if query:
        actor = query[0]
        return render_template("actors/edit.html", actor=actor)
    else:
        return render_template("actors/index.html")


@actors_blueprint.route("/actors/<id>/edit", methods=["POST"])
def update(id):
    actor = Actor.query.get(id)
    try:
        name = (request.form.get("name"),)
        uid = (request.form.get("uid"),)
        filmography_movie_url = (request.form.get("filmography_movie_url"),)
        filmography_movie_title = request.form.get("filmography_movie_title")
        actor.name = name[0]
        actor.uid = uid[0]
        actor.filmography_movie_title = filmography_movie_title[0]
        actor.filmography_movie_url = filmography_movie_url[0]

        db.session.flush()
        db.session.commit()
    except AssertionError as errors:
        return render_template("actors/edit.html", errors=errors)

    return redirect("/actors")


@actors_blueprint.route("/actors/upload", methods=["POST"])
def upload():
    if "file" not in request.files:
        flash("No file part")
        return render_template("/upload/index.html")
    file = request.files["file"]
    if file and allowed_file(file.filename):
        for row in file.readlines():
            temp = json.loads(row)
            actor = Actor()
            actor.name = temp.get("name")
            actor.uid = temp.get("uid")
            actor.filmography_movie_url = str(temp.get("filmography_movie_url"))
            actor.filmography_movie_title = str(temp.get("filmography_movie_title"))

            db.session.add(actor)
        db.session.flush()
        db.session.commit()

        filename = secure_filename(file.filename)
        file.save(os.path.join(app.config["UPLOAD_FOLDER"], filename))
        print(file)
        # ipdb.set_trace()
        flash("Successfully uploaded file")
    else:
        flash("Unallowed file type")
    return render_template("/upload/index.html")

src/presenter/templates/actors/actor.html
{% extends 'homepage/index.html' %}
{% block content %}
<p>Actor</p>
<p>{{actor["name"]}}</p>
<p>Filmography</p>
    	{% for item in actor.filmography %}
	    	<a href="{{ item[1] }}"> {{ item[0] }}  </a> </p>
    	{% endfor %}

<hr>
<a href="{{ url_for('actors.update', id=actor.id) }}">Edit actor</a>
{% endblock %}

src/presenter/templates/actors/edit.html
{% extends 'homepage/index.html' %}
{% block content %}
<p>Change actor {{actor.name}}</p>
    <form method="post" url="{{ url_for('actors.update', id=actor['id']) }}">
        <label for="actor">Actor</label>
        <br>
        <input type="text" name="name" placeholder="name" value ="{{ actor.name }}"></input>
        <input type="text" name="uid" placeholder="uid" value ="{{ actor.uid }}"></input>
        <input type="text" name="filmography_movie_url" placeholder="filmography_movie_url" value ="{{ actor.filmography_movie_url }}"></input>
        <input type="text" name="filmography_movie_title" placeholder="filmography_movie_title" value ="{{ actor.filmography_movie_title }}"></input>
        </input>

        <button type="submit">Submit</button>
    </form>

    {% if errors %}
        {{ errors }}
    {%endif%}
{% endblock %}

src/presenter/templates/actors/index.html
{% extends 'homepage/index.html' %}
{% block content %}
<p>Actors list</p>
<ul id="actors">
    {% if current_page == 1 %}
            <li>
                <a  href="#">Previous</a></li>
    {% else %}
            <li>
                <a href="{{ url_for('actors.index', page=current_page - 1, items=items_per_page) }}">Previous</a></li>
    {% endif %}
     <li>
                <a class="button-next" href="{{ url_for('actors.index', page=current_page + 1, items=items_per_page) }}">Next</a></li>
</ul>

    {% for actor in actors %}
            <p><a href="{{ url_for('actors.show', id=actor.id) }}">{{ actor["name"] }}</a></p> 
    {% endfor %}

<hr>
<a href="/actors/new">Add new actor</a>
{% endblock %}

src/presenter/templates/actors/new.html
{% extends 'homepage/index.html' %}
{% block content %}
<p>Add a new actor</p>
    <form method="post" url='/actors/new'>
        <label for="actor">Actor</label>
        <br>
        <input type="text" name="name" placeholder="name"></input>
        <input type="text" name="uid" placeholder="uid"></input>
        <input type="text" name="filmography_movie_url" placeholder="filmography_movie_url"></input>
        <input type="text" name="filmography_movie_title" placeholder="filmography_movie_title"></input>
        </input>

        <button type="submit">Submit</button>
    </form>

    {% if errors %}
        {{ errors }}
    {%endif%}
{% endblock %}